name: Evolene CI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  Evolene:
    name: Continuous Integration
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Build, Test and Push with Evolene
        run: |
          SLACK_CHANNELS=#team-developers \
          BUILD_INFORMATION_OUTPUT_FILE='/version.conf' \
          PUSH_PUBLIC="True" \
          
          ${{ secrets.EVOLENE_RUN_COMMAND }}
